# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a01e9f3c9b948804db649919546d816c"
name = "centire-first-app"
handle = "centire-first-app"
application_url = "https://cdna-saturday-regulatory-stuffed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abhishek-dev-storee.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_customers,write_orders"

[auth]
redirect_urls = [
  "https://cdna-saturday-regulatory-stuffed.trycloudflare.com/auth/callback",
  "https://cdna-saturday-regulatory-stuffed.trycloudflare.com/auth/shopify/callback",
  "https://cdna-saturday-regulatory-stuffed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
